<?php
/**
 * Created by PhpStorm.
 * User: veades
 * Date: 2015-02-25
 * Time: 4:45 PM
 */


/**
 * Alter the menu tree and its configuration before the tree is rendered.
 *
 * @param $tree
 *   An array containing the unrendered menu tree.
 * @param $config
 *   An array containing the configuration of the tree.
 */
function vpri_menu_block_menu_block_tree_alter(&$tree, &$config) {

    foreach ($tree as $key => &$value) {
        if (!$tree[$key]['link']['hidden']) {
						$tree[$key]['link']['localized_options']['html'] = TRUE;
        }
    }
}


